version: "3.6"
services:
  db:
    image: mariadb
    container_name: "mdb1"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_USER= agsroot
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      - MYSQL_PASSWORD= ags
    ports:
      - "9906:3306"
    volumes:
    - ./data:/var/lib/mysql
    # command: mysqld --innodb-flush-method=O_DSYNC
    command: --default-authentication-plugin=mysql_native_password

  p2app:
    build: .
    links:
      - db
    container_name: "flaskapp"
    ports:
      - "5000:5000"  
    volumes:
      - ./p2app:/p2app

  nginx:
    image: nginx:latest
    links:
      - p2app
    ports:
      - "80:80"